---
spring:
  jpa:
    hibernate.ddl-auto: update
    show_sql: false
---
# Profile used when app deployed on OpenShift
spring.profiles: openshift
spring:
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}
    username: ${mysql.user}
    password: ${mysql.password}
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


