apiVersion: v1
kind: Template
metadata:
  name: cloud-native-backend-template
annotations:
    description: "A SpringBoot microservice which uses MySQL database to store notes and exposes a REST endpoint"
# Parameters
parameters:
- name: ARTIFACT_COPY_ARGS
  description: Syntax to be used to copy uberjar files to the target directory
  displayName: Copy Args
  value: '*-exec.jar'
  required: true
- name: OPENTRACING_JAEGER_SENDER_URL
  description: URL address of the Jaeger HTTP Sender
  displayName: Jaeger URL
  value: 'http://jaeger-collector.infra.svc:14268/api/traces'
  required: true
- name: OPENTRACING_JAEGER_LOG_SPANS
  description: Enable logging of spans
  displayName: Jaeger Log
  value: 'false'
- name: OPENTRACING_JAEGER_SERVICE_NAME
  description: The name of the service as it will show up in Jaeger
  displayName: Jaeger Service Name
  value: 'cloud-native-backend'
# Objects defined for the template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: cloud-native-backend
      group: me.snowdrop
      version: 1.0-SNAPSHOT
    name: cloud-native-backend
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: cloud-native-backend
      group: me.snowdrop
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: cloud-native-backend
      group: me.snowdrop
      version: 1.0-SNAPSHOT
    name: cloud-native-backend
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: cloud-native-backend
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: cloud-native-backend
      group: me.snowdrop
      version: 1.0-SNAPSHOT
    name: cloud-native-backend
  spec:
    replicas: 1
    selector:
      app: cloud-native-backend
      group: me.snowdrop
      version: 1.0-SNAPSHOT
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: cloud-native-backend
          group: me.snowdrop
          version: 1.0-SNAPSHOT
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: SPRING_PROFILES_ACTIVE
            value: openshift
          image: cloud-native-backend:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: cloud-native-backend:latest
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: cloud-native-backend-s2i
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cloud-native-backend:latest
    postCommit: {}
    resources: {}
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        env:
        - name: ARTIFACT_COPY_ARGS
          value: ${ARTIFACT_COPY_ARGS}
        - name: "MAVEN_MIRROR_URL"
          value: "http://nexus.infra.svc:8081/nexus/content/groups/public/"
        from:
          kind: ImageStreamTag
          name: backend-runtime:latest
        incremental: true
      type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: cloud-native-backend
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: backend-runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2-7