apiVersion: v1
kind: BuildConfig
metadata:
  name: cloud-native-backend-changeme
  namespace: changeme
spec:
  source:
    git:
      ref: master
      uri: https://github.com/snowdrop/cloud-native-backend.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
          - name: "OPENSHIFT_NAMESPACE"
            value: "changeme"
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
